framework:
  website: nitro.unjs.io
  version: 2.6

  files:
    - user-id.get.ts
    - routes/index.get.ts
    - routes/user.post.ts
    - nitro.config.ts
    - tsconfig.json
    - package.json

  bootstrap:
    - npm install
    - npm run build

  command: pm2-runtime start .output/server/index.mjs -i $(nproc)
